name: Golang workflow
on:
  pull_request:
  push:
    branches:
      - develop
      - master
  create:
    tags:
      - v*
env:
  CGO_ENABLED: 0
  GO111MODULE: on
jobs:
  lint:
    name: Run the linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
  unit:
    name: Run unit tests
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 1
    steps:
      - uses: actions/checkout@v2
      - run: make unit
  dist:
    name: Build docker image and publish it
    runs-on: ubuntu-latest
    needs: [lint, unit]
    env:
      COMMIT: ${{ github.sha }}
      VERSION: ${{ github.ref }}
    steps:
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: arthureichelberger
          password: ${{ secrets.GHCR_TOKEN }}
      - uses: actions/checkout@v2
      - run: make deploy
